Project1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from polls import views
urlpatterns = patterns('',
 	url(r'^polls/', include('polls.urls',namespace="polls")),
 	url(r'^user/', include('userReg.urls',namespace="userReg")),
    url(r'^admin/', include(admin.site.urls)),


)

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

userReg/urls.py
from django.conf.urls import patterns, url
from userReg import views

urlpatterns = patterns('',
    url(r'^$', views.NewUser, name='index'),
    url(r'^getdetail$',views.GetDetail,name='gdetail'),
    url(r'^userdetail/(?P<user_id>\d+)$', views.result, name='result'),    
)

polls/models.py
from django.db import models

class Poll(models.Model):
	question=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date Published')

	def __unicode__(self):
		return self.question

class Choice(models.Model):
	poll=models.ForeignKey(Poll)
	choice=models.CharField(max_length=200)
	votes=models.IntegerField()
	
	def __unicode__(self):
		return self.choice
# Create your models here.

userReg/models.py
from django.db import models
from django.forms import ModelForm


GENDER_CHOICES=(('M','Male'),('F','Female'))
class UserDetails(models.Model):
	fname=models.CharField(max_length=100)
	lname=models.CharField(max_length=100)
	uname=models.CharField(max_length=100)
	email=models.EmailField();
	
	gender=models.CharField(max_length=1,choices=GENDER_CHOICES)


class UserDetailsForm(ModelForm):
	class Meta:
		model=UserDetails
		fields=['fname','lname','uname','email','gender']

# Create your models here.

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from polls.models import Poll,Choice

def index(request):
	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
	template = loader.get_template('polls/index.html')
	context = RequestContext(request, {
		'latest_poll_list': latest_poll_list,
	})
	return HttpResponse(template.render(context))
def detail(request, poll_id):
    poll=get_object_or_404(Poll,pk=poll_id)
    return render(request,'polls/detail.html',{'poll':poll})

def results(request, poll_id):
    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def vote(request, poll_id):
	p=get_object_or_404(Poll,pk=poll_id)
	try:
		s=p.choice_set.get(pk=request.POST['choice'])
	except (KeyError,Choice.DoesNotExist):
		return render(request,'polls/detail.html',{'poll':p,'error_message':"you didn't select choice.",})
	else:
		s.votes+=1
		s.save()
		return HttpResponseRedirect(reverse('polls:results',args={p.id,}))

# Create your views here.

userReg/views.py
from django.shortcuts import render
from userReg.models import UserDetails
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import ModelForm

class UserDetailsForm(ModelForm):
	class Meta:
		model=UserDetails
		fields=['fname','lname','uname','email','gender']

def NewUser(request):
	form=UserDetailsForm()
	return render(request,'form.html',{'form':form})
def GetDetail(request):
	if(request.method=='POST'):
		fname=request.POST['fname']
		lname=request.POST['lname']
		uname=request.POST['uname']
		email=request.POST['email']
		gender=request.POST['gender']
		nuser=UserDetails(fname=fname,lname=lname,uname=uname,email=email,gender=gender)
		nuser.save()
		return HttpResponseRedirect(reverse('userReg:result',args={nuser.id,}))
def result(request,user_id):
	ruser=UserDetails.objects.get(pk=user_id)
	if not ruser==None:
		return render(request,'result.html',{'user':ruser})

# Create your views here.

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice}}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{%url 'polls:detail' poll.id%}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

userReg/templates/form.html
<html>
<head>
</head>
<body>
<form method="post" action="{% url 'userReg:gdetail' %}">
{%csrf_token%}
{{form.as_p}}
<input type="submit" value="Submit"/>
</form>
</body>
</html>

userReg/templates/result.html
<html>
<body>
<table border=3 >
<tr><td colspan="2" align="center">User Details with USERID {{user.id}}</td></tr>
<tr align="center"><td>First Name</td><td>{{user.fname}}</td></tr>
<tr align="center"><td>Last Name</td><td>{{user.lname}}</td></tr>
<tr align="center"><td>UserName</td><td>{{user.uname}}</td></tr>
<tr align="center"><td>Email</td><td>{{user.email}}</td></tr>
<tr align="center"><td>Gender</td><td>
{%if user.gender == 'F'%}
Female
{%else%}
Male
{%endif%}
</td></tr>
</table>
</body>
</html>